#!/bin/bash

pre="./src/environments"
for file in $(ls "$pre" | grep "\.tpl")
do
    revisedname=$(echo "${pre}/${file}" | sed "s|\.tpl|\.ts|g")
    echo "// File automatically generated by environment script" > "${revisedname}"
    cat  "${pre}/${file}" | 
        sed "s|<backurl>|'http://localhost:${IRSJPY_SERVER_PORT}'|g" |
        sed "s|<locurl>|'http://localhost:${IRSJPY_LOCATION_PORT}'|g" |
        sed "s|<portalurl>|'http://localhost:${IRSJPY_PORTAL_PORT}'|g" |
        sed "s|<appidClientID>|'${APPID_CLIENT_ID}'|g" |
        sed "s|<appidDiscoveryEndpoint>|'${APPID_DISCOVERY_ENDPOINT}'|g" >> "${revisedname}"
done
